// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import model "github.com/Optum/dce/pkg/model"

// Deleter is an autogenerated mock type for the Deleter type
type Deleter struct {
	mock.Mock
}

// DeleteLease provides a mock function with given fields: input
func (_m *Deleter) DeleteLease(input *model.Lease) error {
	ret := _m.Called(input)

	var r0 error
	if rf, ok := ret.Get(0).(func(*model.Lease) error); ok {
		r0 = rf(input)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
