// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import lease "github.com/Optum/dce/pkg/lease"
import mock "github.com/stretchr/testify/mock"

// Deleter is an autogenerated mock type for the Deleter type
type Deleter struct {
	mock.Mock
}

// Delete provides a mock function with given fields: input
func (_m *Deleter) Delete(input *lease.Lease) error {
	ret := _m.Called(input)

	var r0 error
	if rf, ok := ret.Get(0).(func(*lease.Lease) error); ok {
		r0 = rf(input)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
