// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import lease "github.com/Optum/dce/pkg/lease"
import mock "github.com/stretchr/testify/mock"

// Eventer is an autogenerated mock type for the Eventer type
type Eventer struct {
	mock.Mock
}

// LeaseCreate provides a mock function with given fields: _a0
func (_m *Eventer) LeaseCreate(_a0 *lease.Lease) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(*lease.Lease) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
