// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import lease "github.com/Optum/dce/pkg/lease"
import mock "github.com/stretchr/testify/mock"

// WriterDeleter is an autogenerated mock type for the WriterDeleter type
type WriterDeleter struct {
	mock.Mock
}

// Delete provides a mock function with given fields: input
func (_m *WriterDeleter) Delete(input *lease.Lease) error {
	ret := _m.Called(input)

	var r0 error
	if rf, ok := ret.Get(0).(func(*lease.Lease) error); ok {
		r0 = rf(input)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Write provides a mock function with given fields: input, lastModifiedOn
func (_m *WriterDeleter) Write(input *lease.Lease, lastModifiedOn *int64) error {
	ret := _m.Called(input, lastModifiedOn)

	var r0 error
	if rf, ok := ret.Get(0).(func(*lease.Lease, *int64) error); ok {
		r0 = rf(input, lastModifiedOn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
