regions:
  - "global"
  # DCE Principals roles are currently locked down
  # to only access these two regions
  # This significantly reduces the run time of nuke.
{{range .Regions}}  - "{{.}}"
{{end}}

account-blacklist:
  - "{{ .ParentAccountID}}" # Arbitrary production account id

resource-types:
  excludes:
    - S3Object # Let the S3Bucket delete all Objects instead of individual objects (optimization)

accounts:
  "{{ .ID}}": # Child Account
    presets:
    - "sso"
    - "controltower"
    filters:
      IAMPolicy:
        # DCE resources
        - type: "contains"
          value: "{{ .PrincipalPolicy}}"
      IAMRole:
        # DCE resources
        - "{{ .AdminRole}}"
        - "{{ .PrincipalRole}}"
        # AWS Organizations resources
        - type: "contains"
          value: "OrganizationAccountAccessRole"
      IAMRolePolicy:
        # DCE resources
        - type: "contains"
          value: "{{ .AdminRole}}"
        - type: "contains"
          value: "{{ .PrincipalRole}}"
        - type: "contains"
          value: "{{ .PrincipalPolicy}}"
        - property: RoleName
          value: "OrganizationAccountAccessRole"
      IAMRolePolicyAttachment:
        # DCE resources
        - "{{ .PrincipalRole}} -> {{ .PrincipalPolicy}}"
        - property: RoleName
          value: "{{ .AdminRole}}"
        # AWS Organizations resources
        - property: RoleName
          value: "OrganizationAccountAccessRole"

presets:
  sso:
    filters:
      IAMSAMLProvider:
        - type: "regex"
          value: "AWSSSO_.*_DO_NOT_DELETE"
      IAMRole:
        - type: "glob"
          value: "AWSReservedSSO_*"
      IAMRolePolicyAttachment:
        - type: "glob"
          value: "AWSReservedSSO_*"
  controltower:
    filters:
      CloudTrailTrail:
        - type: "contains"
          value: "aws-controltower"
      CloudWatchEventsRule:
        - type: "contains"
          value: "aws-controltower"
      EC2VPCEndpoint:
        - type: "contains"
          value: "aws-controltower"
      EC2VPC:
        - type: "contains"
          value: "aws-controltower"
      OpsWorksUserProfile:
        - type: "contains"
          value: "AWSControlTowerExecution"
      CloudWatchLogsLogGroup:
        - type: "contains"
          value: "aws-controltower"
        - type: "contains"
          value: "AWSControlTowerBP"
      CloudWatchEventsTarget:
        - type: "contains"
          value: "aws-controltower"
      SNSSubscription:
        - type: "contains"
          value: "aws-controltower"
      SNSTopic:
        - type: "contains"
          value: "aws-controltower"
      EC2Subnet:
        - type: "contains"
          value: "aws-controltower"
      ConfigServiceDeliveryChannel:
        - type: "contains"
          value: "aws-controltower"
      ConfigServiceConfigurationRecorder:
        - type: "contains"
          value: "aws-controltower"
      CloudFormationStack:
        - type: "contains"
          value: "AWSControlTower"
      EC2RouteTable:
        - type: "contains"
          value: "aws-controltower"
      LambdaFunction:
        - type: "contains"
          value: "aws-controltower"
      EC2DHCPOption:
        - type: "contains"
          value: "aws-controltower"
      IAMRole:
        - type: "contains"
          value: "aws-controltower"
        - type: "contains"
          value: "AWSControlTower"
      IAMRolePolicyAttachment:
        - type: "contains"
          value: "aws-controltower"
        - type: "contains"
          value: "AWSControlTower"
      IAMRolePolicy:
        - type: "contains"
          value: "aws-controltower"