// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// AccountManager is an autogenerated mock type for the AccountManager type
type AccountManager struct {
	mock.Mock
}

// Setup provides a mock function with given fields: adminRole
func (_m *AccountManager) Setup(adminRole string) error {
	ret := _m.Called(adminRole)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(adminRole)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
