// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import account "github.com/Optum/dce/pkg/account"
import mock "github.com/stretchr/testify/mock"

// Deleter is an autogenerated mock type for the Deleter type
type Deleter struct {
	mock.Mock
}

// DeleteAccount provides a mock function with given fields: i
func (_m *Deleter) DeleteAccount(i *account.Account) error {
	ret := _m.Called(i)

	var r0 error
	if rf, ok := ret.Get(0).(func(*account.Account) error); ok {
		r0 = rf(i)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
