// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import model "github.com/Optum/dce/pkg/model"

// Deleter is an autogenerated mock type for the Deleter type
type Deleter struct {
	mock.Mock
}

// DeleteAccount provides a mock function with given fields: inptut
func (_m *Deleter) DeleteAccount(inptut *model.Account) error {
	ret := _m.Called(inptut)

	var r0 error
	if rf, ok := ret.Get(0).(func(*model.Account) error); ok {
		r0 = rf(inptut)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
