// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import account "github.com/Optum/dce/pkg/account"
import arn "github.com/Optum/dce/pkg/arn"
import mock "github.com/stretchr/testify/mock"

// Manager is an autogenerated mock type for the Manager type
type Manager struct {
	mock.Mock
}

// UpsertPrincipalAccess provides a mock function with given fields: _a0
func (_m *Manager) UpsertPrincipalAccess(_a0 *account.Account) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(*account.Account) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ValidateAccess provides a mock function with given fields: role
func (_m *Manager) ValidateAccess(role *arn.ARN) error {
	ret := _m.Called(role)

	var r0 error
	if rf, ok := ret.Get(0).(func(*arn.ARN) error); ok {
		r0 = rf(role)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
