// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import account "github.com/Optum/dce/pkg/account"
import mock "github.com/stretchr/testify/mock"

// MultipleReader is an autogenerated mock type for the MultipleReader type
type MultipleReader struct {
	mock.Mock
}

// GetAccounts provides a mock function with given fields: query, accounts
func (_m *MultipleReader) GetAccounts(query *account.Account, accounts *account.Accounts) error {
	ret := _m.Called(query, accounts)

	var r0 error
	if rf, ok := ret.Get(0).(func(*account.Account, *account.Accounts) error); ok {
		r0 = rf(query, accounts)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
