// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import account "github.com/Optum/dce/pkg/account"
import mock "github.com/stretchr/testify/mock"

// MultipleReader is an autogenerated mock type for the MultipleReader type
type MultipleReader struct {
	mock.Mock
}

// List provides a mock function with given fields: query
func (_m *MultipleReader) List(query *account.Account) (*account.Accounts, error) {
	ret := _m.Called(query)

	var r0 *account.Accounts
	if rf, ok := ret.Get(0).(func(*account.Account) *account.Accounts); ok {
		r0 = rf(query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*account.Accounts)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*account.Account) error); ok {
		r1 = rf(query)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
