// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import account "github.com/Optum/dce/pkg/account"
import mock "github.com/stretchr/testify/mock"

// ReaderWriterDeleter is an autogenerated mock type for the ReaderWriterDeleter type
type ReaderWriterDeleter struct {
	mock.Mock
}

// DeleteAccount provides a mock function with given fields: i
func (_m *ReaderWriterDeleter) DeleteAccount(i *account.Account) error {
	ret := _m.Called(i)

	var r0 error
	if rf, ok := ret.Get(0).(func(*account.Account) error); ok {
		r0 = rf(i)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAccountByID provides a mock function with given fields: ID, _a1
func (_m *ReaderWriterDeleter) GetAccountByID(ID string, _a1 *account.Account) error {
	ret := _m.Called(ID, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, *account.Account) error); ok {
		r0 = rf(ID, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAccounts provides a mock function with given fields: query, accounts
func (_m *ReaderWriterDeleter) GetAccounts(query *account.Account, accounts *account.Accounts) error {
	ret := _m.Called(query, accounts)

	var r0 error
	if rf, ok := ret.Get(0).(func(*account.Account, *account.Accounts) error); ok {
		r0 = rf(query, accounts)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// WriteAccount provides a mock function with given fields: i, lastModifiedOn
func (_m *ReaderWriterDeleter) WriteAccount(i *account.Account, lastModifiedOn *int64) error {
	ret := _m.Called(i, lastModifiedOn)

	var r0 error
	if rf, ok := ret.Get(0).(func(*account.Account, *int64) error); ok {
		r0 = rf(i, lastModifiedOn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
