// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import model "github.com/Optum/dce/pkg/model"

// Reader is an autogenerated mock type for the Reader type
type Reader struct {
	mock.Mock
}

// GetAccountByID provides a mock function with given fields: accountID, _a1
func (_m *Reader) GetAccountByID(accountID string, _a1 *model.Account) error {
	ret := _m.Called(accountID, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, *model.Account) error); ok {
		r0 = rf(accountID, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAccounts provides a mock function with given fields:
func (_m *Reader) GetAccounts() (*model.Accounts, error) {
	ret := _m.Called()

	var r0 *model.Accounts
	if rf, ok := ret.Get(0).(func() *model.Accounts); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Accounts)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAccountsByPrincipalID provides a mock function with given fields: principalID
func (_m *Reader) GetAccountsByPrincipalID(principalID string) (*model.Accounts, error) {
	ret := _m.Called(principalID)

	var r0 *model.Accounts
	if rf, ok := ret.Get(0).(func(string) *model.Accounts); ok {
		r0 = rf(principalID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Accounts)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(principalID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAccountsByStatus provides a mock function with given fields: status
func (_m *Reader) GetAccountsByStatus(status string) (*model.Accounts, error) {
	ret := _m.Called(status)

	var r0 *model.Accounts
	if rf, ok := ret.Get(0).(func(string) *model.Accounts); ok {
		r0 = rf(status)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Accounts)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(status)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
