// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import model "github.com/Optum/dce/pkg/model"

// ReaderWriterDeleter is an autogenerated mock type for the ReaderWriterDeleter type
type ReaderWriterDeleter struct {
	mock.Mock
}

// DeleteAccount provides a mock function with given fields: inptut
func (_m *ReaderWriterDeleter) DeleteAccount(inptut *model.Account) error {
	ret := _m.Called(inptut)

	var r0 error
	if rf, ok := ret.Get(0).(func(*model.Account) error); ok {
		r0 = rf(inptut)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAccountByID provides a mock function with given fields: accountID, _a1
func (_m *ReaderWriterDeleter) GetAccountByID(accountID string, _a1 *model.Account) error {
	ret := _m.Called(accountID, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, *model.Account) error); ok {
		r0 = rf(accountID, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAccounts provides a mock function with given fields: _a0
func (_m *ReaderWriterDeleter) GetAccounts(_a0 *model.Account) (*model.Accounts, error) {
	ret := _m.Called(_a0)

	var r0 *model.Accounts
	if rf, ok := ret.Get(0).(func(*model.Account) *model.Accounts); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Accounts)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*model.Account) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAccountsByStatus provides a mock function with given fields: status
func (_m *ReaderWriterDeleter) GetAccountsByStatus(status string) (*model.Accounts, error) {
	ret := _m.Called(status)

	var r0 *model.Accounts
	if rf, ok := ret.Get(0).(func(string) *model.Accounts); ok {
		r0 = rf(status)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Accounts)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(status)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// WriteAccount provides a mock function with given fields: input, lastModifiedOn
func (_m *ReaderWriterDeleter) WriteAccount(input *model.Account, lastModifiedOn *int64) error {
	ret := _m.Called(input, lastModifiedOn)

	var r0 error
	if rf, ok := ret.Get(0).(func(*model.Account, *int64) error); ok {
		r0 = rf(input, lastModifiedOn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
