// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import model "github.com/Optum/dce/pkg/model"

// Reader is an autogenerated mock type for the Reader type
type Reader struct {
	mock.Mock
}

// GetAccountByID provides a mock function with given fields: accountID
func (_m *Reader) GetAccountByID(accountID string) (*model.Account, error) {
	ret := _m.Called(accountID)

	var r0 *model.Account
	if rf, ok := ret.Get(0).(func(string) *model.Account); ok {
		r0 = rf(accountID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Account)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(accountID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAccounts provides a mock function with given fields: _a0
func (_m *Reader) GetAccounts(_a0 *model.Account) (*model.Accounts, error) {
	ret := _m.Called(_a0)

	var r0 *model.Accounts
	if rf, ok := ret.Get(0).(func(*model.Account) *model.Accounts); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Accounts)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*model.Account) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
