// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import account "github.com/Optum/dce/pkg/account"
import mock "github.com/stretchr/testify/mock"

// SingleReader is an autogenerated mock type for the SingleReader type
type SingleReader struct {
	mock.Mock
}

// GetAccountByID provides a mock function with given fields: ID, _a1
func (_m *SingleReader) GetAccountByID(ID string, _a1 *account.Account) error {
	ret := _m.Called(ID, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, *account.Account) error); ok {
		r0 = rf(ID, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
