// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import model "github.com/Optum/dce/pkg/model"

// SingleReader is an autogenerated mock type for the SingleReader type
type SingleReader struct {
	mock.Mock
}

// GetAccountByID provides a mock function with given fields: accountID
func (_m *SingleReader) GetAccountByID(accountID string) (*model.Account, error) {
	ret := _m.Called(accountID)

	var r0 *model.Account
	if rf, ok := ret.Get(0).(func(string) *model.Account); ok {
		r0 = rf(accountID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Account)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(accountID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
