// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import account "github.com/Optum/dce/pkg/account"
import mock "github.com/stretchr/testify/mock"

// WriterDeleter is an autogenerated mock type for the WriterDeleter type
type WriterDeleter struct {
	mock.Mock
}

// Delete provides a mock function with given fields: i
func (_m *WriterDeleter) Delete(i *account.Account) error {
	ret := _m.Called(i)

	var r0 error
	if rf, ok := ret.Get(0).(func(*account.Account) error); ok {
		r0 = rf(i)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Write provides a mock function with given fields: i, lastModifiedOn
func (_m *WriterDeleter) Write(i *account.Account, lastModifiedOn *int64) error {
	ret := _m.Called(i, lastModifiedOn)

	var r0 error
	if rf, ok := ret.Get(0).(func(*account.Account, *int64) error); ok {
		r0 = rf(i, lastModifiedOn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
