// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import db "github.com/Optum/Redbox/pkg/db"
import mock "github.com/stretchr/testify/mock"

// Provisioner is an autogenerated mock type for the Provisioner type
type Provisioner struct {
	mock.Mock
}

// ActivateAccountAssignment provides a mock function with given fields: _a0, _a1, _a2
func (_m *Provisioner) ActivateAccountAssignment(_a0 bool, _a1 string, _a2 string) (*db.RedboxAccountAssignment, error) {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 *db.RedboxAccountAssignment
	if rf, ok := ret.Get(0).(func(bool, string, string) *db.RedboxAccountAssignment); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*db.RedboxAccountAssignment)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(bool, string, string) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindUserActiveAssignment provides a mock function with given fields: _a0
func (_m *Provisioner) FindUserActiveAssignment(_a0 string) (*db.RedboxAccountAssignment, error) {
	ret := _m.Called(_a0)

	var r0 *db.RedboxAccountAssignment
	if rf, ok := ret.Get(0).(func(string) *db.RedboxAccountAssignment); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*db.RedboxAccountAssignment)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindUserAssignmentWithAccount provides a mock function with given fields: _a0, _a1
func (_m *Provisioner) FindUserAssignmentWithAccount(_a0 string, _a1 string) (*db.RedboxAccountAssignment, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *db.RedboxAccountAssignment
	if rf, ok := ret.Get(0).(func(string, string) *db.RedboxAccountAssignment); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*db.RedboxAccountAssignment)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RollbackProvisionAccount provides a mock function with given fields: _a0, _a1, _a2
func (_m *Provisioner) RollbackProvisionAccount(_a0 bool, _a1 string, _a2 string) error {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 error
	if rf, ok := ret.Get(0).(func(bool, string, string) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
