// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// LeaseReader is an autogenerated mock type for the LeaseReader type
type LeaseReader struct {
	mock.Mock
}
