// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import usage "github.com/Optum/dce/pkg/usage"

// LeaseReaderWriter is an autogenerated mock type for the LeaseReaderWriter type
type LeaseReaderWriter struct {
	mock.Mock
}

// Write provides a mock function with given fields: i
func (_m *LeaseReaderWriter) Write(i *usage.Lease) error {
	ret := _m.Called(i)

	var r0 error
	if rf, ok := ret.Get(0).(func(*usage.Lease) error); ok {
		r0 = rf(i)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
