// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import usage "github.com/Optum/dce/pkg/usage"

// MultipleReader is an autogenerated mock type for the MultipleReader type
type MultipleReader struct {
	mock.Mock
}

// List provides a mock function with given fields: query
func (_m *MultipleReader) List(query *usage.Usage) (*usage.Usages, error) {
	ret := _m.Called(query)

	var r0 *usage.Usages
	if rf, ok := ret.Get(0).(func(*usage.Usage) *usage.Usages); ok {
		r0 = rf(query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*usage.Usages)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*usage.Usage) error); ok {
		r1 = rf(query)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
