// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// SingleReader is an autogenerated mock type for the SingleReader type
type SingleReader struct {
	mock.Mock
}
