// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import credentials "github.com/aws/aws-sdk-go/aws/credentials"
import mock "github.com/stretchr/testify/mock"

// Credentialer is an autogenerated mock type for the Credentialer type
type Credentialer struct {
	mock.Mock
}

// Get provides a mock function with given fields:
func (_m *Credentialer) Get() (credentials.Value, error) {
	ret := _m.Called()

	var r0 credentials.Value
	if rf, ok := ret.Get(0).(func() credentials.Value); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(credentials.Value)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
