// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import credentials "github.com/aws/aws-sdk-go/aws/credentials"
import mock "github.com/stretchr/testify/mock"
import time "time"

// Credentialer is an autogenerated mock type for the Credentialer type
type Credentialer struct {
	mock.Mock
}

// ExpiresAt provides a mock function with given fields:
func (_m *Credentialer) ExpiresAt() (time.Time, error) {
	ret := _m.Called()

	var r0 time.Time
	if rf, ok := ret.Get(0).(func() time.Time); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(time.Time)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Get provides a mock function with given fields:
func (_m *Credentialer) Get() (credentials.Value, error) {
	ret := _m.Called()

	var r0 credentials.Value
	if rf, ok := ret.Get(0).(func() credentials.Value); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(credentials.Value)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IsExpired provides a mock function with given fields:
func (_m *Credentialer) IsExpired() bool {
	ret := _m.Called()

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}
