pool:
  vmImage: "Ubuntu 16.04"

trigger:
  # Do not build branches
  branches:
    exclude:
      - "*"
  # Run build on tagged versions
  tags:
    include:
      - "v*"

# Run builds for PRs against `master`
pr:
  - master
  - release/*

steps:
  - bash: |
      # TODO tag name can't be namespace, AWS doesn't like
      # it as a resource name.
      # If it's a tagged version, just call it `release` or something
      if [[ -z ${PR_NUMBER} ]]; then
        NS="release"
      else
        NS="github-pr-${PR_NUMBER}"
      fi

      echo "Namespace is ${NS}"

      # Set the namespace as a Azure Pipeline variable
      # See https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#set-in-script
      echo "##vso[task.setvariable variable=namespace]${NS}"
    displayName: "Configure AWS Namespace"
    env:
      PR_NUMBER: $(System.PullRequest.PullRequestNumber)
      # This is the branch name, or the git tag name
      NS_BRANCH_OR_TAG: $(Build.SourceBranchName)