// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import usage "github.com/Optum/dce/pkg/usage"

// Servicer is an autogenerated mock type for the Servicer type
type Servicer struct {
	mock.Mock
}

// UpsertLeaseUsage provides a mock function with given fields: data
func (_m *Servicer) UpsertLeaseUsage(data *usage.Usage) (*usage.Usage, error) {
	ret := _m.Called(data)

	var r0 *usage.Usage
	if rf, ok := ret.Get(0).(func(*usage.Usage) *usage.Usage); ok {
		r0 = rf(data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*usage.Usage)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*usage.Usage) error); ok {
		r1 = rf(data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
