// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import usage "github.com/Optum/dce/pkg/usage"

// Servicer is an autogenerated mock type for the Servicer type
type Servicer struct {
	mock.Mock
}

// UpsertLeaseUsage provides a mock function with given fields: data
func (_m *Servicer) UpsertLeaseUsage(data *usage.Lease) error {
	ret := _m.Called(data)

	var r0 error
	if rf, ok := ret.Get(0).(func(*usage.Lease) error); ok {
		r0 = rf(data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
