// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Builder is an autogenerated mock type for the Builder type
type Builder struct {
	mock.Mock
}

// StartBuild provides a mock function with given fields: projectName, environmentVariables
func (_m *Builder) StartBuild(projectName *string, environmentVariables map[string]string) (string, error) {
	ret := _m.Called(projectName, environmentVariables)

	var r0 string
	if rf, ok := ret.Get(0).(func(*string, map[string]string) string); ok {
		r0 = rf(projectName, environmentVariables)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*string, map[string]string) error); ok {
		r1 = rf(projectName, environmentVariables)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
