// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Storager is an autogenerated mock type for the Storager type
type Storager struct {
	mock.Mock
}

// Download provides a mock function with given fields: bukcet, key, filepath
func (_m *Storager) Download(bukcet string, key string, filepath string) error {
	ret := _m.Called(bukcet, key, filepath)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string) error); ok {
		r0 = rf(bukcet, key, filepath)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetObject provides a mock function with given fields: bucket, key
func (_m *Storager) GetObject(bucket string, key string) (string, error) {
	ret := _m.Called(bucket, key)

	var r0 string
	if rf, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = rf(bucket, key)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(bucket, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTemplateObject provides a mock function with given fields: bucket, key, input
func (_m *Storager) GetTemplateObject(bucket string, key string, input interface{}) (string, string, error) {
	ret := _m.Called(bucket, key, input)

	var r0 string
	if rf, ok := ret.Get(0).(func(string, string, interface{}) string); ok {
		r0 = rf(bucket, key, input)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 string
	if rf, ok := ret.Get(1).(func(string, string, interface{}) string); ok {
		r1 = rf(bucket, key, input)
	} else {
		r1 = ret.Get(1).(string)
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(string, string, interface{}) error); ok {
		r2 = rf(bucket, key, input)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Upload provides a mock function with given fields: bucket, key, filepath
func (_m *Storager) Upload(bucket string, key string, filepath string) error {
	ret := _m.Called(bucket, key, filepath)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string) error); ok {
		r0 = rf(bucket, key, filepath)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
