// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import account "github.com/Optum/dce/pkg/account"

import mock "github.com/stretchr/testify/mock"

// AccountData is an autogenerated mock type for the AccountData type
type AccountData struct {
	mock.Mock
}

// Delete provides a mock function with given fields: _a0
func (_m *AccountData) Delete(_a0 *account.Account) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(*account.Account) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields: ID
func (_m *AccountData) Get(ID string) (*account.Account, error) {
	ret := _m.Called(ID)

	var r0 *account.Account
	if rf, ok := ret.Get(0).(func(string) *account.Account); ok {
		r0 = rf(ID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*account.Account)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(ID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: query
func (_m *AccountData) List(query *account.Account) (*account.Accounts, error) {
	ret := _m.Called(query)

	var r0 *account.Accounts
	if rf, ok := ret.Get(0).(func(*account.Account) *account.Accounts); ok {
		r0 = rf(query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*account.Accounts)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*account.Account) error); ok {
		r1 = rf(query)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Write provides a mock function with given fields: _a0, prevLastModifiedOn
func (_m *AccountData) Write(_a0 *account.Account, prevLastModifiedOn *int64) error {
	ret := _m.Called(_a0, prevLastModifiedOn)

	var r0 error
	if rf, ok := ret.Get(0).(func(*account.Account, *int64) error); ok {
		r0 = rf(_a0, prevLastModifiedOn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
