// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UsagePrincipal is an autogenerated mock type for the UsagePrincipal type
type UsagePrincipal struct {
	mock.Mock
}
