// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import usage "github.com/Optum/dce/pkg/usage"

// UsageLease is an autogenerated mock type for the UsageLease type
type UsageLease struct {
	mock.Mock
}

// Write provides a mock function with given fields: usg
func (_m *UsageLease) Write(usg *usage.Lease) error {
	ret := _m.Called(usg)

	var r0 error
	if rf, ok := ret.Get(0).(func(*usage.Lease) error); ok {
		r0 = rf(usg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
