// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import usage "github.com/Optum/dce/pkg/usage"

// UsageData is an autogenerated mock type for the UsageData type
type UsageData struct {
	mock.Mock
}

// Get provides a mock function with given fields: startDate, principalID
func (_m *UsageData) Get(startDate int64, principalID string) (*usage.Usage, error) {
	ret := _m.Called(startDate, principalID)

	var r0 *usage.Usage
	if rf, ok := ret.Get(0).(func(int64, string) *usage.Usage); ok {
		r0 = rf(startDate, principalID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*usage.Usage)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int64, string) error); ok {
		r1 = rf(startDate, principalID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: query
func (_m *UsageData) List(query *usage.Usage) (*usage.Usages, error) {
	ret := _m.Called(query)

	var r0 *usage.Usages
	if rf, ok := ret.Get(0).(func(*usage.Usage) *usage.Usages); ok {
		r0 = rf(query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*usage.Usages)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*usage.Usage) error); ok {
		r1 = rf(query)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Write provides a mock function with given fields: _a0
func (_m *UsageData) Write(_a0 *usage.Usage) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(*usage.Usage) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
