// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import config "github.com/Optum/dce/pkg/config"
import mock "github.com/stretchr/testify/mock"

// ConfigurationServiceBuilder is an autogenerated mock type for the ConfigurationServiceBuilder type
type ConfigurationServiceBuilder struct {
	mock.Mock
}

// WithService provides a mock function with given fields: svc
func (_m *ConfigurationServiceBuilder) WithService(svc interface{}) *config.ConfigurationBuilder {
	ret := _m.Called(svc)

	var r0 *config.ConfigurationBuilder
	if rf, ok := ret.Get(0).(func(interface{}) *config.ConfigurationBuilder); ok {
		r0 = rf(svc)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*config.ConfigurationBuilder)
		}
	}

	return r0
}
