// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ConfigurationBuildBuilder is an autogenerated mock type for the ConfigurationBuildBuilder type
type ConfigurationBuildBuilder struct {
	mock.Mock
}

// Build provides a mock function with given fields:
func (_m *ConfigurationBuildBuilder) Build() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewConfigurationBuildBuilder interface {
	mock.TestingT
	Cleanup(func())
}

// NewConfigurationBuildBuilder creates a new instance of ConfigurationBuildBuilder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewConfigurationBuildBuilder(t mockConstructorTestingTNewConfigurationBuildBuilder) *ConfigurationBuildBuilder {
	mock := &ConfigurationBuildBuilder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
