// Code generated by mockery 2.7.4. DO NOT EDIT.

package mocks

import (
	config "github.com/Optum/dce/pkg/config"
	mock "github.com/stretchr/testify/mock"
)

// ConfigurationServiceBuilder is an autogenerated mock type for the ConfigurationServiceBuilder type
type ConfigurationServiceBuilder struct {
	mock.Mock
}

// Build provides a mock function with given fields:
func (_m *ConfigurationServiceBuilder) Build() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// WithService provides a mock function with given fields: svc
func (_m *ConfigurationServiceBuilder) WithService(svc interface{}) *config.ConfigurationBuilder {
	ret := _m.Called(svc)

	var r0 *config.ConfigurationBuilder
	if rf, ok := ret.Get(0).(func(interface{}) *config.ConfigurationBuilder); ok {
		r0 = rf(svc)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*config.ConfigurationBuilder)
		}
	}

	return r0
}
