name: Nonprod PR Pipeline

on:
  pull_request:
    types: [ opened, synchronize, reopened, closed ]
    branches:
      - master

jobs:
  build:
    uses: ./.github/workflows/pipeline.yaml
    with:
      environment: nonprod
      version_tag: pr-${{ github.event.number }}
      namespace: pr-${{ github.event.number }}
    secrets:
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      DCE_NONPROD_HOSTNAME: ${{ secrets.DCE_NONPROD_HOSTNAME }}
      NOTIFY_EMAIL: ${{ secrets.NOTIFY_EMAIL }}
