name: DCE deploy to environment

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
        description: "The environment to deploy to (e.g. nonprod, prod)"
        default: "nonprod"
      branch:
        required: false
        type: string
        default: master
      release:
        required: false
        type: string
        default: none
      go_version:
        required: false
        type: string
        default: "1.21.6"
      terraform_version:
        required: false
        type: string
        default: "1.7.4"
      version_tag:
        required: false
        type: string
        default: master # pr-#, nonprod, or vX.Y.Z
      namespace:
        required: false
        type: string
        default: nonprod # pr-#, nonprod, or prod
    secrets:
      AWS_DEFAULT_REGION:
        required: true
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      DCE_NONPROD_HOSTNAME:
        required: true
      NOTIFY_EMAIL:
        required: true
jobs:
  Release:
    needs: [Deploy]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download bin artifact
        uses: actions/download-artifact@v4
        with:
          name: bin
          path: ${{ github.workspace }}/bin

      - name: Download deploy_scripts artifact
        uses: actions/download-artifact@v4
        with:
          name: deploy_scripts
          path: ${{ github.workspace }}/deploy_scripts

      - name: Verify artifacts
        run: |
          ls -l ${{ github.workspace }}/bin
          ls -l ${{ github.workspace }}/deploy_scripts

      - name: Create GitHub Release
        if: github.event_name != 'pull_request'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          draft: false
          prerelease: false
          files: |
            ${{ github.workspace }}/bin/build_artifacts.zip
            ${{ github.workspace }}/bin/terraform_artifacts.zip
            ${{ github.workspace }}/deploy_scripts/deploy.sh
            ${{ github.workspace }}/deploy_scripts/restore_db.sh
